name: Feature request
description: Suggest an idea for this project
labels: enhancement

body:
  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: |
        Suggest your feature here. What benefit would it bring?
        
        Do you have any ideas on how to implement it?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
      description: Suggest any alternative solutions or features you've considered.
  - type: textarea
    id: other-info
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
